export const CLASS_ICONS = {
  'Bord': 'table-furniture',
  'Byrå': 'dresser',
  'Bänk': 'table-picnic',
  'Fåtölj': 'seat',
  'Hylla': 'bookshelf',
  'Kista': 'archive',
  'Lampa': 'lamp',
  'Matta': 'texture-box',
  'Pall': 'stool',
  'Porslin': 'cup',
  'Skåp': 'file-cabinet',
  'Skänk': 'wardrobe',
  'Soffa': 'sofa',
  'Spegel': 'mirror',
  'Stol': 'chair-school',
  'Säng': 'bed',
  'TV-bänk': 'television-classic',
  'Vagn': 'cart',
  'Vas': 'flower',
  'Övrigt': 'help-circle',
};
